name: CI/CD

on:
    push: 
        branches:
            - main
    pull_request:
      types: [opened, reopened]

jobs:
    CI:
        name: Continuous Integration
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 22.x

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test
    CD:
        name: Continuous Delivery
        runs-on: ubuntu-latest

        needs: CI

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 22.x
            
            - name: Setup EAS
              uses: expo/expo-github-action@v8
              with:
                eas-version: latest
                package: npm
                token: ${{ secrets.EAS_EXPO_TOKEN }}

            - name: Get Config File
              run: |
                echo $GOOGLE_SERVICES_64 > google-services.json.b64
                base64 -d -i google-services.json.b64 > google-services.json
              env:
                GOOGLE_SERVICES_64: ${{ secrets.EAS_GOOGLE_PLAY_API }}

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: eas build --platform android --profile production --non-interactive --no-wait
              env:
                EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}